project:
  type: book
  output-dir: docs

book:
  title: "Building a Research Website with Quarto"
  author: "Vanessa Quintana"
  chapters:
    - index.qmd
    - 01-getting-started.qmd
    - 02-structure.qmd
    - 03-editing.qmd
    - 04-styling.qmd
    - 05-publishing.qmd
number-sections: true

format:
  html:
    theme: [flatly, custom.scss]
    css: styles.css
    toc: true
    toc-depth: 2

execute:
  freeze: auto